[package]
name = "plc-logger-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.4.0", features = ["tray-icon"] }
tauri-plugin-dialog = { version = "2.4.0" }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }
